#spring:    
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: N/D
      
server:
  port: 8081
  
kafka:
  server:
    endpoint: 127.0.0.1:9092
  topic: CDM-DEV-JAVA_EXAMPLE_PROJECT-SKRC-TOPIC    
  
#logging:
#  level:
#    root: WARN
#    '[org.springframework]': WARN
#    '[org.springframework.boot.web.embedded.tomcat.TomcatWebServer]': INFO
#    '[com.claudiodimauro]': DEBUG  